### ISSUE TITLE
adts_test_ in test/proper_tests.erl times out on slower arches

### ISSUE THREAD

**Issue by bowlofeggs** [proper-testing/proper#139] opened 2017-02-20 03:15 UTC
Hello!

I am the package maintainer for proper in Fedora, and I've found that ```adts_test_``` in ```test/proper_tests.erl``` will fail on two arches: ```armv7hl``` and ```aarch64``` due to the test timing out. The test runner will end like this:

```
    proper_tests:1020: options_test_...[0.005 s] ok
    proper_tests:1023: options_test_...[0.005 s] ok
    proper_tests:1026: options_test_...[0.001 s] ok
    proper_tests:1027: options_test_...[0.001 s] ok
    proper_tests:1028: options_test_...[0.001 s] ok
    proper_tests:1029: options_test_...ok
    proper_tests:1032: options_test_...[0.001 s] ok
    proper_tests:1046: adts_test_...[0.250 s] ok
    proper_tests:1049: adts_test_...*timed out*
undefined
=======================================================
  Failed: 0.  Skipped: 0.  Passed: 447.
One or more tests were cancelled.
DEBUG: Reconstruct stdlib []
DEBUG: Reconstruct kernel [{error_logger,tty}]
DEBUG: Reconstruct rebar [{log_level,warn},
                          {log_colored,uncolored},
                          {any_dir_modules,
                              [rebar_require_vsn,rebar_deps,rebar_subdirs,
                               rebar_templater,rebar_cleaner]},
                          {modules,
                              [{app_dir,
                                   [rebar_proto_compiler,
                                    rebar_protobuffs_compiler,
                                    rebar_neotoma_compiler,
                                    rebar_asn1_compiler,rebar_dia_compiler,
                                    rebar_dialyzer,rebar_erlc_compiler,
                                    rebar_lfe_compiler,rebar_erlydtl_compiler,
                                    rebar_port_compiler,rebar_otp_app,
                                    rebar_otp_appup,rebar_ct,rebar_eunit,
                                    rebar_qc,rebar_escripter,rebar_edoc,
                                    rebar_shell,rebar_xref,rebar_metacmds]},
                               {rel_dir,
                                   [rebar_appups,rebar_reltool,
                                    rebar_upgrade]}]},
                          {recursive_cmds,
                              ['check-deps',compile,'delete-deps','get-deps',
                               'list-deps','update-deps']}]
ERROR: One or more eunit tests failed.
ERROR: eunit failed while processing /builddir/build/BUILD/proper-1.2: rebar_abort
```

I've worked around this by renaming the test to adts_dontrun_ with sed when the test suite is run on these arches, but if there's a way for us to extend the timeout so the test can complete that would be helpful. Thanks!

**Comment by kostis** [comment] 2017-02-21 21:48
Thanks for filing this issue and for maintaining PropEr in Fedora.  We can of course fix this timeout, however not for the tagged 1.2 version which we cannot/do not want to change anymore.  What we can do is create a new tagged version (e.g. 1.2.1 or even 1.3) from the current master which, besides having new goodies, will up the timeout value for this test.  What is the time window for making it into the next Fedora release?

**Comment by bowlofeggs** [comment] 2017-02-22 16:35
Hello @kostis!

I wouldn't expect you to change the 1.2 tag as in my view version tags should be immutable, so that's no problem at all. I wouldn't put any rush on fixing this issue - I've got a workaround that just skips this test on two arches (it still gets run on the rest of our arches).

The next release is Fedora 26, which will branch from Rawhide next week on Tuesday. I can put a bugfix release into it (or into Fedora 24 and 25) after that date easily, but I usually try to avoid putting backwards imcompatible releases into existing Fedora releases. So as long as 1.2.1 or 1.3 are backwards compatible, I can release it at any time.

Again, don't feel a huge rush about this, I just wanted to let you know ☺

**Comment by kostis** [comment] 2017-02-22 21:48
Try to see if when you can take / apply the change in the #141 pull request, the problem gets solved on these slow machines.  If not, please report here the values for which the issue is resolved.

**Comment by bowlofeggs** [comment] 2017-02-23 03:22
@kostis This seems to do the trick, thanks!

I will carry this patch downstream until your next release. Thus, there's no rush to make a release unless you just want to ☺

**Comment by kostis** [comment] 2017-02-24 11:17
I managed to find an `aarch64` machine and discovered that it was actually the third test of `adts_test` that was the culprit and needed an increased timeout value.  Can you please test again the #141 pull request?

**Comment by kostis** [comment] 2022-06-13 19:23
Fixed in master.

**Closed by kostis** 2022-06-13 19:23 UTC
